---
- name: Setup environment for three-tier application
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker.io
        - docker-compose

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install Maven
      apt:
        name: maven
        state: present
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nodejs
        - npm

    - name: Install Python and pip
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-pip

    - name: Reload systemd state
      systemd:
        daemon_reload: yes

    - name: Copy docker-compose.yml to target host
      copy:
        src: ./docker-compose.yml
        dest: /home/jenkins/docker-compose.yml

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/jenkins
